### ISSUE TITLE
Error detection peripheral

### ISSUE THREAD

**Issue by totpero** [sanchezzzhak/node-device-detector#93]
Hi,
I implement the  [.NET version](https://github.com/totpero/DeviceDetector.NET) and I have the same scenario like you.
For this exemple:
[Mozilla/5.0 (X11; Linux x86_64; ricoh_mfpapnl) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/11.0.696.34 Safari/534.24](https://iehol.sse.codesandbox.io/#Mozilla/5.0%20(X11;%20Linux%20x86_64;%20ricoh_mfpapnl)%20AppleWebKit/534.24%20(KHTML,%20like%20Gecko)%20Chrome/11.0.696.34%20Safari/534.24)
Is detected like device type: "desktop" but is "peripheral"
  
```
user_agent: Mozilla/5.0 (X11; Linux x86_64; ricoh_mfpapnl) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/11.0.696.34 Safari/534.24
  os:
    name: GNU/Linux
    version: ""
    platform: x64
  client:
    type: browser
    name: Chrome
    version: 11.0.696.34
    engine: WebKit
    engine_version: "534.24"
  device:
    type: peripheral
    brand: Ricoh
    model: MFP
  os_family: GNU/Linux
  browser_family: Chrome
```

The php version detect [this](https://devicedetector.lw1.at/Mozilla%2F5.0%20(X11;%20Linux%20x86_64;%20ricoh_mfpapnl)%20AppleWebKit%2F534.24%20(KHTML,%20like%20Gecko)%20Chrome%2F11.0.696.34%20Safari%2F534.24)
The problem is [here hasDesktopFragment](https://github.com/matomo-org/device-detector/blob/master/Parser/Device/AbstractDeviceParser.php#L1550)
